Update for 1.20.6.
SakuraKoi/meowil-box pull request #4
Opened 2024-06-14 05:47 UTC by qyl27

And disabled SakuraKooi specific package skin because someone dislike it,

2024-08-30 11:12 UTC, SakuraKoi requested changes, later dismissed
Do not merge it into upstream, keep it in fork

2024-08-30 16:36 UTC, SakuraKoi requested changes

2024-08-30 16:36 UTC, SakuraKoi commented on src/main/java/dev/sakurakooi/spigot/meowilbox/inv/holders/MeowilBoxSendHolder.java
> -            storage.getContents().add(ItemBuilder.createItemPackage(sender, content, isAuthor));
Do not merge it into upstream

2024-08-31 04:41 UTC, qyl27 commented
Moved to #5

2024-08-31 04:41 UTC, closed without merging